In [2]:
import torch
import torch.nn as nn
from SDT import SDT
from torch.utils import data
from utils.dataset import Dataset
import numpy as np
from sdt_train import learner_args

learner_args['depth']=3
tree = SDT(learner_args)

# for layer_weight, value in tree.state_dict().items():
#     print(layer_weight, value.shape)
    
inner_nodes = tree.state_dict()['inner_nodes.linear.weight']
leaf_nodes = tree.state_dict()['leaf_nodes.weight']

begin_idx = 0
end_idx = 1

for layer_idx in range(0, learner_args['depth']):
    print(inner_nodes[begin_idx:end_idx])
    begin_idx = end_idx
    end_idx = begin_idx + 2 ** (layer_idx+1)

tensor([[-0.1171, -0.0783,  0.1687, -0.1234,  0.2853,  0.0426, -0.1773, -0.1596,
          0.1021]])
tensor([[-0.1917, -0.3272,  0.2618, -0.1237,  0.2995,  0.0664,  0.1746,  0.1112,
         -0.2843],
        [ 0.3086, -0.0770, -0.0686,  0.0974, -0.1494,  0.3106,  0.0823, -0.1762,
          0.1523]])
tensor([[ 0.0065,  0.1377,  0.2026, -0.1703,  0.2634, -0.1045, -0.2916, -0.0411,
          0.2966],
        [-0.0119, -0.2444, -0.2529,  0.0334, -0.3090, -0.0870, -0.3063, -0.1637,
         -0.1708],
        [ 0.2364,  0.0115, -0.2835,  0.3311, -0.1806, -0.2963, -0.1432, -0.2028,
         -0.0045],
        [-0.0155, -0.2072, -0.0548, -0.2329, -0.0898,  0.0816, -0.2549,  0.0020,
          0.1453]])


In [22]:
a=torch.Tensor([[1,2],[2,3]])
v, i = torch.max(a, 1)
print(v,i)
a.scatter_(1, i.view(-1,1), 0.)

tensor([2., 3.]) tensor([1, 1])


tensor([[1., 0.],
        [2., 0.]])